services:
  api-1:
    build: .
    ports:
      - "8081:8080"
    container_name: api-1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_rinha2025
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - JAVA_OPTS=-Xmx130m -Xms130m -XX:+UseContainerSupport
    networks:
      - app
      - payment-processor
    depends_on:
      db:
        condition: service_healthy



  api-2:
    build: .
    ports:
      - "8082:8080"
    container_name: api-2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_rinha2025
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - JAVA_OPTS=-Xmx130m -Xms130m -XX:+UseContainerSupport
    networks:
      - app
      - payment-processor
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:17-alpine
    container_name: db_rinha_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_rinha2025
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c 'max_connections=180' -c 'shared_buffers=12MB'

  load-balancer:
    container_name: load-balancer-nginx
    image: nginx:1.27.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:9999"
    networks:
      - app

networks:
  app:
    driver: bridge
  payment-processor:
    external: true